services:
  - type: web
    name: gemi-bot
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: poetry run gunicorn main:web_app --bind 0.0.0.0:$PORT -k aiohttp.GunicornWebWorker
    envVars:
      - key: ENV
        sync: false
      - key: APP_HOSTNAME
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: MSG_HANDLING_CONCURRENCY
        value: 10
      - key: INACTIVITY_SLEEP_DELAY
        value: 30
    healthCheckPath: /ping

  - type: web
    name: gemi-voice
    runtime: docker
    region: singapore
    plan: free
    repo: https://github.com/Akash98Sky/gemi-voice.git
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /ping